version: '3.7'

services:
    app_placer:
        image: tmp:latest
        command: placer -p 1337 --database /opt/server/database.db
        ports:
            - 1337:1337
        volumes:
            - './.backend/placer:/opt/server'
        build:
            context: betting-runner

    app_server:
        # Fixes permission errors, TODO: Fix
        user: root:root
        image: tmp:latest
        command: server /opt/server -o /opt/node-exporter/test.prom
        volumes:
            - './.backend/runner/datasources:/opt/server'
            - './.backend/node-exporter:/opt/node-exporter'
        build:
            context: betting-runner

    app_stocks:
        image: tmp:latest
        command: stocks --dev --offline -t meow --symbol AMZN --symbol MSFT
        ports:
            - 8080:8080
        build:
            context: betting-runner

    prometheus:
        image: prom/prometheus:latest
        ports:
            - 9090:9090
        volumes:
            - './.backend/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'

    node-exporter:
        # Fixes permission errors, TODO: Fix
        user: root:root
        image: prom/node-exporter:latest
        volumes:
            - ./.backend/node-exporter/:/etc/node-exporter/
        command:
            - '--collector.textfile.directory=/etc/node-exporter/'

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes:
            - './.backend/grafana/provisioning/:/etc/grafana/provisioning/'
        environment:
            # Anonymous Users are by default viewers in the main organisation
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_SECURITY_ALLOW_EMBEDDING=true